name: kima
description: A new Flutter project.
publish_to: "none"
version: 1.0.4+4

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  bloc: ^8.1.2
  camera: ^0.10.5+5
  carousel_slider: ^4.2.1
  chopper: ^7.0.6
  cloud_firestore: ^4.13.5
  crypto: ^3.0.3
  cupertino_icons: ^1.0.6
  dio: ^5.4.0
  dotted_border: ^2.1.0
  encrypt: ^5.0.3
  equatable: ^2.0.5
  firebase_analytics: ^10.5.0
  firebase_auth: ^4.12.1
  firebase_core: ^2.16.0
  firebase_crashlytics: ^3.3.6
  firebase_database: ^10.3.6
  firebase_performance: ^0.9.2+6
  flutter_bloc: ^8.1.3
  flutter_cache_manager: ^3.3.1
  flutter_dotenv: ^5.1.0
  flutter_facebook_auth: ^6.0.3
  flutter_image_compress: ^2.1.0
  flutter_keyboard_visibility: ^5.4.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_stripe: ^10.0.0
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.2
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.5
  http: ^1.1.0
  http_parser: ^4.0.2
  image_gallery_saver: ^2.0.3
  image_picker: ^1.0.4
  intl: ^0.18.1
  intl_phone_field: ^3.2.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  jwt_decoder: ^2.0.1
  mobile_scanner: ^3.5.5
  package_info_plus: ^4.1.0
  path: ^1.8.3
  path_provider: ^2.1.1
  qr_flutter: ^4.0.0
  share_plus: ^7.1.0
  shared_preferences: ^2.2.1
  sign_in_with_apple: ^5.0.0
  timeago: ^3.6.0
  uni_links: ^0.5.1
  url_launcher: ^6.2.1
  video_player: ^2.4.7
  webview_flutter: 3.0.4

dev_dependencies:
  # dart run build_runner build --delete-conflicting-outputs
  build_runner: ^2.4.6
  chopper_generator: ^7.0.4
  flutter_gen_runner: ^5.3.2
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.3
  flutter_native_splash: ^2.3.2
  flutter_test:
    sdk: flutter

flutter_gen:
  integrations:
    flutter_svg: true

flutter:
  uses-material-design: true

  assets:
    - assets/.env
    - assets/icons/
    - assets/icons/authentication/
    - assets/icons/bottom_navigation/
    - assets/svg/
    - assets/temporary/
  #  fonts:
  #    - family: ProximaNova
  #      fonts:
  #        - asset: assets/fonts/Proxima-Nova-Font.otf
  # Change application launcher icon run the commands
#   flutter pub get
#   dart run flutter_launcher_icons
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: assets/icons/launcher_icon.png
  remove_alpha_ios: true
  min_sdk_android: 21
  # This package generates native code to customize Flutter's default white native splash screen
  # with background color and splash image.
  # Customize the parameters below, and run the following command in the terminal:
  # dart run flutter_native_splash:create
  # To restore Flutter's default white splash screen, run the following command in the terminal:
  # dart run flutter_native_splash:remove
  #    flutter pub get
  #    dart run flutter_native_splash:create
  #flutter_native_splash:
  #  android: true
  #  ios: true
  #  web: true
  #  color: "#000000"
  #  image: assets/icons/launcher_icon.png
  #  android_gravity: fill
  ##  ios_content_mode: scaleToFill
  ##  web_image_mode: contain
  ##  fullscreen: true
  #  android_12:
  #    image: assets/icons/launcher_icon.png
  # image_dark: assets/images/launcher_icon.png
  # Splash screen background color.
  # color: "#000000"
  # App icon background color.
  # icon_background_color_dark: "#000000"
  # icon_background_color: "#000000"
